### ISSUE TITLE
dropdown always display blank when first load

### ISSUE THREAD

**Issue by yofret** [SpoonX/aurelia-autocomplete#37]
Hi, first of all thanks for this awesome component, I'm having an issue with the autocomplete, I have a fixed set of items in an array, but every time the page loads, it always show de dropdown with no items like this:

![screen shot 2017-10-11 at 4 36 50 pm](https://user-images.githubusercontent.com/11755802/31468314-e26ea61e-aea2-11e7-8231-858b3add23ad.png)

this is my code:
html
```
...
<auto-complete items.bind="skills" value.two-way="skill" placeholder="Enter Skill" limit="10" ></auto-complete>
...
```
js
```
export class testComponent {
  constructor(config, router) {
    this.skills = ['Painting', 'Programing'];
  }
}
```

Any ideas to fix this?

Thanks!

**Comment by RWOverdijk** [comment]
It needs to be a @bindable. Read the aurelia docs for more. But basically:

```js
export class testComponent {
  @bindable skills = ['Painting', 'Programing'];

  constructor(config, router) {
  }
}
```

**Comment by yofret** [comment]
Hi, Thanks for the reply, I added as @bindable, but the issue is still happening, I tried different parameters and can't seems to get it work normally

**Comment by RWOverdijk** [comment]
@yofret I'm not sure then. That should work. As long as the info is there it should populate.

@jeremyvergnas ideas?

**Comment by jeremyvergnas** [comment]
I just tried it, seems to work fine (Only tested it on Chrome).

**Comment by yofret** [comment]
@RWOverdijk It populates normally, the issue is the white rectangle there in the screenshot, It will disappear when the input gains focus, otherwise it will stay there forever

**Comment by ItWorksOnMyMachine** [comment]
Same issue for me.  This happens in all browsers.  The binding works fine, it's just that when I first load the page, every autocomplete has the "No results" list item visible.  It appears that the show binding on the list item is wrong.  

show.bind="results.length === 0 && !lastFindPromise"

The problem here is that lastFindPromise isn't defined on the component's view model until the first call to valueChanged, which doesn't happen until the the first setFocus call.  So any input box that hasn't yet had the focus set will get that little "No results" list item because lastFindPromise is undefined and type coersion's truthyness converts undefined to false.  At least, that's how I read the code...  Maybe try this:

show.bind="results.length === 0 && lastFindPromise != undefined && !lastFindPromise"

**Comment by RWOverdijk** [comment]
Ah that makes more sense. It shouldn't show anything until it's ready. That also explains the PR better.

**Comment by RWOverdijk** [comment]
Try v2.2.3.

Thanks for the help @ItWorksOnMyMachine you're awesome
